name: DJ ACRAIG
favicon: null
layout_spectrum: 0.02853194996714592
typography_spectrum: 0.3903865066822618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5747495864052325
  lightness: 0.6254097779747099
  saturation: 0.06113707716576755
  rhythmicContrast: 0.28662897157482803
purpose: []
